#!/bin/sh
# File generated by ocamlbuild

cd /Users/swarnpriya/Desktop/Purdue_research/git-repos/ocaml-irmin/ppx-ocaml-4.06-irmin-1.4.0/test/list

rm -f msigs.cmi
rm -f msigs.cmx
rm -f msigs.o
# Also clean the script itself
rm -f /Users/swarnpriya/Desktop/Purdue_research/git-repos/ocaml-irmin/ppx-ocaml-4.06-irmin-1.4.0/test/list/_build/sanitize.sh
